name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "latest"
          purs-tidy: "latest"
          spago: "unstable"

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Build source
        run: spago build --censor-stats --strict --pedantic-packages

      - name: Run tests
        run: spago test --censor-stats --strict --pedantic-packages

      - name: Verify formatting
        run: purs-tidy check src test
